spring.application.name=restStudy
server.port=8080

logging.level.org.springframework=info
logging.level.org.springframework.web=info


# Database Setthing
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://54.206.114.153:3306:3306/study
spring.datasource.username=root
spring.datasource.password=Qwer1234!

# JPA Satting
# - Console SQL112
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect